### ISSUE TITLE
DownloadCreateTicket,与FileGet问题

### ISSUE THREAD

**Issue by user1121114685** [deadblue/elevengo#11]
FileGet 始终返回 json格式化错误。    

---
DownloadCreateTicket 中的 DownloadTicket缺少关键cookie    

https://webapi.115.com/files/download?pickcode 后有个 Set-Cookie 请将这个cookie 加入 DownloadTicket 中取代 原有的cookie.    
而使用 https://proapi.115.com/app/chrome/downurl? 没有这个cookie

**Comment by user1121114685** [comment]
` n.prototype.formatCookies = function () {
        var e = [];
        for (var t in this.cookies) e.push(t + "=" + this.cookies[t]);
        return e.join("; ")`

https://github.com/acgotaku/115/blob/44c965a75e4bffbbfd9293419b0b4d413ff3f318/release/js/home.js#L1  
这里有JS实现方法，可以参考

**Comment by deadblue** [comment]
`FileGet`的问题已经在 develop 分支修复。

下载所需的所有 Cookie， 都已拼成请求头，放在 `DownloadTicket.Headers` 中了：https://github.com/deadblue/elevengo/blob/develop/download.go#L75-L87
在使用第三方工具下载的时候，直接用 Headers 中的内容即可：
<img width="610" alt="download-sample" src="https://user-images.githubusercontent.com/2597868/169946983-d3885ddf-53d2-4c05-a4a5-476af79ca83e.png">

"https://webapi.115.com/files/download" 会返回一个针对下载路径的特殊 cookie，不过 "https://proapi.115.com/app/chrome/downurl" 并不返回：
<img width="851" alt="set-cookie" src="https://user-images.githubusercontent.com/2597868/169944330-65f9b0e1-3555-46b1-84a9-1c4d35099359.png">

**Comment by user1121114685** [comment]
`{"status":403,"message":"invalid signature","request_id":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}`   
 
我查看每次调用的cookie都是登陆的cookie 这与aria2推送的特殊coookie并不相符，我使用给定的cookie返回的就是这个。我还是认为 下载的cookie 不是登陆的cookie 应该还是需要特殊的cookie

**Comment by user1121114685** [comment]
`http://proapi.115.com/app/chrome/downurl`中有返回的 特殊cookie，我看看能不能修改下！！！

**Comment by user1121114685** [comment]
`http://proapi.115.com/app/chrome/downurl`中有返回的 特殊cookie，我看看能不能修改下！！！

**Comment by user1121114685** [comment]
是我虚妄了。原来签名验证还包含这些。谢谢指点
