### ISSUE TITLE
烦请问有无支持提供 HTTP API 的意向

### ISSUE THREAD

**Issue by LuneZ99** [deadblue/elevengo#37]
目前看到最棒的类似库！如果能为各个功能提供 http api 的话，就可以以服务的形式自己部署在服务器上，让不同语言或者多个程序同时调用这个服务 ——这样就太棒了。

感谢作者的辛苦开发！

**Comment by user1121114685** [comment]
想要什么功能自己写就是了，大佬路都铺平了。

**Comment by deadblue** [comment]
哦，我一开始理解是支持以 HTTP 方式调用 115 API，这个确实有计划做，因为 HTTP 通信的性能比 HTTPS 好一些。

但是封装成 HTTP API 这个暂时没计划，这个项目仅作为 SDK ，供别人基于它开发上层程序。
