### ISSUE TITLE
大佬，你好我找了一下没有找到支持秒传。请问下有打算支持吗？

### ISSUE THREAD

**Issue by user1121114685** [deadblue/elevengo#4]
PS 我也可以帮忙一起做！

**Comment by deadblue** [comment]
develop 分支的 Agent.Import 方法就是用来秒传的，见: [import.go:43](https://github.com/deadblue/elevengo/blob/develop/import.go#L43)

目前 dev 版本还差一些功能没完成，等完成后会合并到 master 分支，然后出一个 release 版本，预计这两天吧。

**Comment by deadblue** [comment]
已发布 v0.2.1 版本，对应 API 见：
https://pkg.go.dev/github.com/deadblue/elevengo#Agent.Import

对于秒传链接，需要自行解析，并填充`ImportTicket`结构体，然后传给`Import`方法。

**Comment by user1121114685** [comment]
大佬 辛苦了！~
