### ISSUE TITLE
大佬，辛苦了。昨天我测试妙传使用GitHub 开发者分支，出现签名错误。

### ISSUE THREAD

**Issue by user1121114685** [deadblue/elevengo#44]
第一次提交就出现了。本来应该第一次抛出range 第二次成功，
实际上，第一次报错签名错误

**Comment by deadblue** [comment]
我也遇到过类似的问题，尝试重新扫码登录，生成一个 Credential 就能解决。

因为 Agent 每次创建时会自动取 115 的最新的 Linux 桌面客户端版本号作为 AppVersion。
因此可能出现这种情况：
- 扫码登录导出 Credential 时， AppVersion 是 A 。
- 上传的时候 AppVersion 是 B。
推测是115服务端检测了 Credential 对应的 App Version。

要避免这个问题，可以在创建 Agent 的时候传入 option.AgentVersionOption("XX.X.X") 锁定版本号。
