### ISSUE TITLE
不支持多平台登录了吗

### ISSUE THREAD

**Issue by ipv4sec** [deadblue/elevengo#48]

**Comment by deadblue** [comment]
115 下架了三个平台的桌面客户端，对应的接口也不能用了……

**Comment by ipv4sec** [comment]
https://alist.nn.ci/zh/guide/drivers/115.html#_3-%E4%BD%BF%E7%94%A8python%E8%84%9A%E6%9C%AC%E8%8E%B7%E5%8F%96-cookie

这里有好多平台

**Comment by deadblue** [comment]
> https://alist.nn.ci/zh/guide/drivers/115.html#_3-%E4%BD%BF%E7%94%A8python%E8%84%9A%E6%9C%AC%E8%8E%B7%E5%8F%96-cookie
> 
> 这里有好多平台

其他平台的登录接口我没抓过，我参考一下那个脚本，谢谢~

**Comment by ipv4sec** [comment]
感谢您的辛苦工作
