### ISSUE TITLE
是不是目前High-level API中的FileIterate还不支持分页获取？

### ISSUE THREAD

**Issue by cnazev** [deadblue/elevengo#52]
我看方法参数以及方法里的 
	fi := &fileIterator{
		llc:   a.llc,
		dirId: dirId,
		mode:  1,
	}
并没有分页相关数据

**Comment by deadblue** [comment]
High Level 中的 Iterator 就是返回所有数据的，不支持分页，如需分页建议使用 Low Level API。

**Comment by cnazev** [comment]
多谢， 在用Low Level API分页了， 不过我看fileIterator的定义里有 offset, limit int，后续会支持？

**Comment by deadblue** [comment]
fileIterator 存储 offset 和 limit，是用来记住当前所在页，当用户遍历完本页数据时，fileIterator 会自动调用接口去取下一页的文件数据：
https://github.com/deadblue/elevengo/blob/v0.7.4/file.go#L206

在 High-Level API 支持分页，这个我考虑一下：）

**Comment by cnazev** [comment]
多谢
