### ISSUE TITLE
关于添加离线任务 OfflineAddUrl 这个方法的返回

### ISSUE THREAD

**Issue by cnazev** [deadblue/elevengo#53]
官方添加时如果遇到相同url会提示 error_msg: "任务已存在"，不会创建任务（返回里确实也有info_hash）。
目前咱这个库，貌似处理上有点不完善？
我测试了下看还是返回了一个hash，没有提示重复，未创建。

**Comment by user1121114685** [comment]
你就提交个pr完善一下呗。作者精力也有限

**Comment by cnazev** [comment]
嗯 可以考虑下

**Comment by deadblue** [comment]
当初这么设计，是考虑到大部分用户的需求只是创建任务，即使出现了“任务已存在“这个错误，这个离线任务在云端还是有了。
而且返回 info hash，方便开发者通过 info hash 来获取任务详细信息。

我回顾了一下这部分代码，Low-level API 不该内部消化这个错误，应该返回给开发者。
High-level API 的目标是覆盖常见需求，因此 High-level API 会暂时保留这个设计。
