### ISSUE TITLE
还打算继续支持更多接口吗

### ISSUE THREAD

**Issue by lowking** [deadblue/elevengo#54]
https://webapi.115.com/share/snap
搜不到保存分享相关的接口呢

**Comment by lowking** [comment]
感谢，今天写机器人发现保存分享的没有，不知道还缺少其他的没，之后继续反馈，辛苦了😁

**Comment by deadblue** [comment]
保存分享文件的 API，已经在 v0.7.5 中添加。
Post 接口预计在下个版本中开放。
