### ISSUE TITLE
已保存的cookie重新导入调用接口会提示用户没登录

### ISSUE THREAD

**Issue by lowking** [deadblue/elevengo#55]
第一次扫码成功登录之后保存uid cid seid之后重新登录，调用listFileSpec会提示user not login。和朋友对比了下似乎少一个kid？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by deadblue** [comment]
这种错误是是 cookie 失效导致的。

115 限制一个账号在一个客户端只能登录一次。比如你先通过扫码登录方式获取了 web 端的 cookie，并保存了下来。之后同一个账号又通过扫码登录了一次 web 端，则前一次的 cookie 就会被标记为失效。

**Comment by deadblue** [comment]
看了一下，KID 应该是新增的 Cookie，我之前扫码拿到的 Cookie 只有 UID/CID/SEID 三个字段，可以正常用，新生成的 Cookie 必须带 KID。

我更新一下。

**Comment by deadblue** [comment]
v0.7.6 已修复。

**Comment by lowking** [comment]
测试目前没撒问题
能不能添加下我定义的新的错误，我机器人登录逻辑有用到🤣

**Comment by deadblue** [comment]
40101004 和 50199004，这两个错误码是什么状况下触发的？

**Comment by lowking** [comment]
40101004：我测试东西一直扫码，然后请求接口一直user not login，次数多了之后被风控的吧，提示“ip登录异常，请稍后再试”。
50199004：这个也是同一时期出现的好像，日志的输入信息就是get failed。
还有一个ErrQrcodeCancelled，日志输出没有code，只有错误信息QRcode cancelled

**Comment by deadblue** [comment]
0.7.7 版本增加了这两个错误码对应的错误。

"QRcode cancelled" 错误是我这边返回的，不是115服务端：
https://github.com/deadblue/elevengo/blob/09da5bae7bde7329bf8f41a64e0af0ec5f24e3d5/qrcode.go#L47

**Comment by lowking** [comment]
哈哈哈哈，原来不在一个文件里
